apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls
  namespace: argocd
spec:
  secretName: argocd-tls
  commonName: argocd.delaparra.local
  dnsNames:
    - argocd.delaparra.local
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
