# Builder stage
FROM debian:12 AS builder

WORKDIR /opt/hb

RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential cmake git pkg-config ncurses-dev libssl-dev \
        libradosstriper-dev librocksdb-dev curl make git gcc nodejs npm \
        curl ca-certificates wget gnupg && rm -rf /var/lib/apt/lists/*

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y


RUN git clone https://github.com/erlang/otp.git && cd otp && git checkout maint-28  && ./configure && make && make install

# Install rebar3
RUN curl  https://github.com/erlang/rebar3/releases/latest/download/rebar3 -o /usr/local/bin/rebar3 && \
    chmod +x /usr/local/bin/rebar3 && \
    rebar3 version

RUN /usr/local/bin/rebar3 release | tee /opt/hb/rebar3_build.log

# Runtime stage
FROM debian:12
RUN apt-get update && apt-get install -y --no-install-recommends \
        curl ca-certificates wget gnupg librocksdb-dev erlang-base \
        erlang-nox && rm -rf /var/lib/apt/lists/*

# Copy built application from builder stage
COPY --from=builder /opt/hb /opt/hb

# Set working directory
WORKDIR /opt/hb

# Configuration and data directories
VOLUME ["/data"]
ENV HB_STORE_PATH=/data
ENV HB_KEY=/secrets/wallet.json

# Expose the application port
EXPOSE 8734

# Run the application
CMD ["tail", "-f", "/dev/null"]
#CMD ["./bin/hb", "foreground"]