apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyperbeam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hyperbeam
  template:
    metadata:
      labels:
        app: hyperbeam
    spec:
      containers:
        - name: hb
          image: ${DOCKER_IMAGE}
          ports:
            - containerPort: 8734
          env:
            - name: HB_STORE_PATH
              value: /var/lib/hb
            - name: HB_KEY
              value: /secrets/wallet.json
            - name: HB_CONFIG_LOCATION
              value: /config/config.flat
          volumeMounts:
            - name: wallet
              mountPath: /secrets
              readOnly: true
            - name: config
              mountPath: /config
              readOnly: true
            - name: data
              mountPath: /data
          livenessProbe:
            httpGet:
              path: /~meta@1.0/info
              port: 8734
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /~meta@1.0/info
              port: 8734
            initialDelaySeconds: 30
          resources:
            requests:
              cpu: "500m"
              memory: "2Gi"
            limits:
              cpu: "2000m"
              memory: "8Gi"
      volumes:
        - name: wallet
          secret:
            secretName: hyperbeam-wallet
        - name: config
          secret:
            secretName: hyperbeam-config